PROGDIR: /usr/local/cckiller
LOGDIR: /usr/local/cckiller/log
PROG: /usr/local/cckiller/cckiller
IGNORE_IP_LIST: /usr/local/cckiller/ignore.ip.list
IPT: /sbin/iptables
DKName: CCKiller
DKVer: 1.0.8
SLEEP_TIME: '20'
NO_OF_CONNECTIONS: '100'
EMAIL_TO: '"root@localhost"'
BAN_PERIOD: '600'
IGNORE_PORT: ''
LOG_LEVEL: INFO
__shard_r0_duplicate:
  PROGDIR: /usr/local/cckiller
  LOGDIR: /usr/local/cckiller/log
  PROG: /usr/local/cckiller/cckiller
  IGNORE_IP_LIST: /usr/local/cckiller/ignore.ip.list
  IPT: /sbin/iptables
  DKName: CCKiller
  DKVer: 1.0.8
  SLEEP_TIME: '20'
  NO_OF_CONNECTIONS: '100'
  EMAIL_TO: '"root@localhost"'
  BAN_PERIOD: '600'
  IGNORE_PORT: ''
  LOG_LEVEL: INFO
